-- ═══════════════════════════════════════════════════════════════════════════
-- MIMAREK — Row Level Security (RLS) Setup
-- Run after `prisma db push` in Supabase SQL Editor (Dashboard → SQL Editor → New query),
-- on every environment (production + any long-lived staging DB).
-- ═══════════════════════════════════════════════════════════════════════════
--
-- STRATEGY
-- --------
-- Mimarek is a pure server-side app (Next.js + Prisma). All database access
-- goes through the `postgres` role via the Supabase connection pooler. That role
-- OWNS these tables and therefore bypasses RLS automatically — no policies are
-- needed for the app to function.
--
-- Enabling RLS without permissive policies achieves two goals:
--   1. Silences the Supabase security advisor (`rls_disabled_in_public`).
--   2. Denies all PostgREST (anon / authenticated) access by default, closing the
--      auto-generated REST API surface to unauthenticated or client-side queries.
--      The public `NEXT_PUBLIC_SUPABASE_ANON_KEY` cannot read or write any row.
--
-- If a future feature requires direct Supabase client access (e.g. realtime
-- subscriptions, public marketplace served via PostgREST), add explicit policies
-- for ONLY those tables at that time — never a blanket permissive policy.
--
-- EXPECTED ADVISOR NOISE — DO NOT "FIX": after this runs, the Supabase advisor
-- reports `rls_enabled_no_policy` (INFO) on every table here. That is the intended
-- state — RLS-on + no-policy IS the firewall. DO NOT silence it by adding a
-- permissive policy (`USING (true)`); that re-opens the PostgREST/anon surface and
-- undoes the whole point. The owner (`postgres`) already bypasses RLS, so the app
-- needs no policy to function. Accept the INFO; never trade it for a policy.
--
-- DO NOT use ALTER TABLE ... FORCE ROW LEVEL SECURITY — that forces the owning
-- `postgres` role through policies that don't exist, which would break every
-- Prisma query. ENABLE (not FORCE) is the firewall; the owner still bypasses it.
--
-- Idempotent: `ENABLE ROW LEVEL SECURITY` is a no-op when already enabled, and
-- `IF EXISTS` skips tables absent on a given environment. Safe to re-run.
--
-- COVERAGE CONTRACT: this file must list EVERY table in schema.prisma plus the
-- implicit M2M join table(s) and Prisma's internal table (AGENTS.md §4).
-- THIS FILE IS GENERATED by scripts/generate-rls.ts from schema.prisma — do NOT
-- edit it by hand. When you add, rename, or remove a model, regenerate it in the
-- same change:  cd packages/db && npx tsx scripts/generate-rls.ts --write
-- CI runs `--check` and fails on any drift between this file and schema.prisma.
-- All table names are double-quoted: unquoted mixed-case identifiers fold to
-- lowercase, making `ALTER TABLE IF EXISTS` silently no-op (never enable RLS).
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Tables (schema.prisma model order) ───────────────────────────────────────
ALTER TABLE IF EXISTS public."Organization"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."User"                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SavedTableView"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Unit"                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Customer"                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Reservation"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ReservationExtension"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Contract"                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PaymentPlan"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PaymentPlanInstallment"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ContractTemplate"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Lease"                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RentInstallment"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RentPayment"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Document"                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."MaintenanceRequest"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PreventiveMaintenancePlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PasswordResetToken"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."EmailVerificationToken"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AuditLog"                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ConsentLog"                ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Notification"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PermissionRequest"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SupportTicket"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."TicketMessage"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Invitation"                ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."JoinRequest"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DocumentVersion"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Plan"                      ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PlanEntitlement"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Subscription"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SubscriptionEvent"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SubscriptionMrrSnapshot"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."EntitlementOverride"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Invoice"                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."InvoiceLineItem"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PaymentTransaction"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."PaymentMethod"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GatewayConfig"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."WebhookEvent"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DataRetentionRun"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Coupon"                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CouponRedemption"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CustomerActivity"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CustomerPropertyInterest"  ENABLE ROW LEVEL SECURITY; -- model Deal (@@map)
ALTER TABLE IF EXISTS public."SystemConfig"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."MarketplaceListing"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."MarketplaceInquiry"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."UnitTransferTransaction"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."MarketplaceDeedProof"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."OrgRegaAuthorization"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SequenceCounter"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."RateLimitCounter"          ENABLE ROW LEVEL SECURITY;

-- ── Non-model tables ─────────────────────────────────────────────────────────
ALTER TABLE IF EXISTS public."_CouponPlans"              ENABLE ROW LEVEL SECURITY; -- implicit M2M join table (Plan ↔ Coupon)
ALTER TABLE IF EXISTS public."_prisma_migrations"        ENABLE ROW LEVEL SECURITY; -- Prisma internal

-- ── Verification (optional) — every public table should report relrowsecurity = true ──
-- SELECT relname, relrowsecurity
-- FROM pg_class
-- WHERE relnamespace = 'public'::regnamespace AND relkind = 'r'
-- ORDER BY relrowsecurity, relname;
